# Generated by Django 3.1.5 on 2021-01-19 10:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20210118_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=20)),
                ('remark', models.CharField(default='None', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='remark',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='filldate',
            field=models.DateField(default=datetime.datetime(2021, 1, 19, 10, 9, 38, 479631, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='pay_methold',
            field=models.CharField(choices=[('remit', '匯款'), ('check', '支票'), ('cash', '現金')], default='remit', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='serial_num',
            field=models.CharField(max_length=15),
        ),
    ]
