# Generated by Django 3.1.5 on 2021-01-21 15:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_auto_20210120_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='filldate',
            field=models.DateField(default=datetime.datetime(2021, 1, 21, 15, 5, 5, 12335, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('remark', models.CharField(default='N/A', max_length=50)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('invoice_sn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.invoice')),
            ],
        ),
    ]
