# Generated by Django 3.1.5 on 2021-01-22 14:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_auto_20210121_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='filldate',
            field=models.DateField(default=datetime.datetime(2021, 1, 22, 14, 5, 16, 242282, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice_sn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice'),
        ),
    ]
