# Generated by Django 3.1.5 on 2021-01-25 07:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_auto_20210122_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='purpose',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='filldate',
            field=models.DateField(default=datetime.datetime(2021, 1, 25, 7, 35, 50, 807272, tzinfo=utc)),
        ),
    ]
