# Generated by Django 3.1.5 on 2021-01-25 08:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_auto_20210125_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='remark',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='filldate',
            field=models.DateField(default=datetime.datetime(2021, 1, 25, 8, 12, 30, 125279, tzinfo=utc)),
        ),
    ]
