# Generated by Django 3.1.5 on 2021-01-27 10:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_delete_item_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pay_currency',
            field=models.CharField(choices=[('新台幣', '新台幣'), ('美金', '美金'), ('歐元', '歐元'), ('人民幣', '人民幣')], default='新台幣', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='filldate',
            field=models.DateField(default=datetime.datetime(2021, 1, 27, 10, 2, 39, 773419, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
